### ISSUE TITLE
합치고 회원가입 안됨

### ISSUE THREAD

**Issue by somfist** [clonecoding1/carrotmarket-FE#16]
그러나 회원가입 완료되었다고 alert뜸

**Comment by somfist** [comment]
1. alert는 수정예정
2. FE측에서 confirmPassword라는 데이터를 보내고  BE측에서 confirmPassword를 보내는 줄몰라서 미들웨어에서 걸림 => 해결완료

**Comment by Changsoon-Yun** [comment]
확인해씁니다
