### ISSUE TITLE
home 화면에서 페이지가 여러개인 상황

### ISSUE THREAD

**Issue by somfist** [clonecoding1/carrotmarket-FE#32]
위 상황에서 페이징이 4라고 할때 12를 누르면 빈화면이 보임

원석님 처리중

**Comment by wonseok-do** [comment]
페이지끝자릿수에서 게시물 수를 수정할 경우 페이지끝자릿수가 존재하지 않을 경우 빈페이지가 뜸-> onChange에서 setPage(1)를 추가하여 강제로 페이지1로 가게하여 해결함
